// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpcmfAvwSutc0aEIS7GCwIxM0YyGnupS4',
    appId: '1:1045273047204:web:0d9ccd962cb2955107b631',
    messagingSenderId: '1045273047204',
    projectId: 'finalprojectmgads',
    authDomain: 'finalprojectmgads.firebaseapp.com',
    storageBucket: 'finalprojectmgads.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuU-jj5FJihIdHiZH_jRwIerL2PNs0KZE',
    appId: '1:1045273047204:android:b88b89d6f3cafd8007b631',
    messagingSenderId: '1045273047204',
    projectId: 'finalprojectmgads',
    storageBucket: 'finalprojectmgads.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQpV5kvyPkncjCIgzUG7kogqiJPXTfMxc',
    appId: '1:1045273047204:ios:a50c916b0fa1329607b631',
    messagingSenderId: '1045273047204',
    projectId: 'finalprojectmgads',
    storageBucket: 'finalprojectmgads.appspot.com',
    iosBundleId: 'com.example.finalProjectV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQpV5kvyPkncjCIgzUG7kogqiJPXTfMxc',
    appId: '1:1045273047204:ios:6d6f361a23dbea6a07b631',
    messagingSenderId: '1045273047204',
    projectId: 'finalprojectmgads',
    storageBucket: 'finalprojectmgads.appspot.com',
    iosBundleId: 'com.example.finalProjectV1.RunnerTests',
  );
}
